import sgMail from "@sendgrid/mail";

const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;
const FROM_EMAIL = process.env.SENDGRID_FROM_EMAIL || "reports@casocomply.com";
const BASE_URL = process.env.NEXT_PUBLIC_VERCEL_URL
  ? `https://${process.env.NEXT_PUBLIC_VERCEL_URL}`
  : process.env.NEXT_PUBLIC_BASE_URL || "https://caso-comply.vercel.app";

if (SENDGRID_API_KEY) {
  sgMail.setApiKey(SENDGRID_API_KEY);
}

export async function sendReportEmail({
  to,
  scanId,
  domain,
  overallGrade,
  overallScore,
  pdfCount,
  analyzedCount,
}: {
  to: string;
  scanId: string;
  domain: string;
  overallGrade: string;
  overallScore: number;
  pdfCount: number;
  analyzedCount: number;
}): Promise<boolean> {
  if (!SENDGRID_API_KEY) {
    console.warn("SENDGRID_API_KEY not set — skipping email");
    return false;
  }

  const reportUrl = `${BASE_URL}/report/${scanId}`;

  const gradeColors: Record<string, string> = {
    A: "#10B981",
    B: "#2EA3F2",
    C: "#EAB308",
    F: "#EF4444",
  };
  const gradeColor = gradeColors[overallGrade] || gradeColors.F;

  const msg = {
    to,
    from: { email: FROM_EMAIL, name: "CASO Comply" },
    subject: `Your PDF Compliance Audit — ${domain}`,
    html: [
      '<div style="font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px 24px; background: #0B1D3A; color: #FFFFFF;">',
      '  <div style="text-align: center; margin-bottom: 32px;">',
      '    <h1 style="font-size: 24px; margin: 0;">PDF Compliance Audit</h1>',
      `    <p style="color: #94A3B8; margin-top: 8px; font-size: 14px;">${domain}</p>`,
      "  </div>",
      '  <div style="text-align: center; padding: 24px; background: #132D54; border-radius: 12px; margin-bottom: 24px;">',
      `    <div style="display: inline-block; width: 80px; height: 80px; border-radius: 50%; border: 4px solid ${gradeColor}; line-height: 72px; font-size: 32px; font-weight: bold; color: ${gradeColor};">`,
      `      ${overallGrade}`,
      "    </div>",
      `    <p style="margin: 12px 0 0; font-size: 18px; font-weight: bold;">${overallScore}/100 Overall Score</p>`,
      `    <p style="color: #94A3B8; margin: 8px 0 0; font-size: 14px;">${analyzedCount} of ${pdfCount} PDFs analyzed</p>`,
      "  </div>",
      '  <div style="text-align: center; margin: 32px 0;">',
      `    <a href="${reportUrl}" style="display: inline-block; background: #2EA3F2; color: #FFFFFF; padding: 16px 32px; border-radius: 12px; text-decoration: none; font-weight: bold; font-size: 16px;">View Full Report</a>`,
      "  </div>",
      '  <p style="color: #94A3B8; font-size: 12px; text-align: center;">This report was generated by CASO Comply. Share this link with your team — no login required.</p>',
      "</div>",
    ].join("\n"),
  };

  try {
    await sgMail.send(msg);
    return true;
  } catch (err) {
    console.error("SendGrid send error:", err);
    return false;
  }
}
